alias l="ls -lh --time-style='+%d.%m.%Y %R'"
alias ll="ls -lhA --time-style='+%d.%m.%Y %R'"

alias code="flatpak run com.vscodium.codium"

alias f="find . -name"

alias g="git"
alias gs="git status -sb"
alias gst="git status"
alias gd="git diff"
alias ga="git add"
gc() {
  git commit -m "$*"
}
alias gp="git push"
alias gl="git log --oneline -8"
alias gll="git log --stat"
alias gla="git log -1 --stat"
alias gn="git checkout -b"
alias gch="git checkout"
alias gchl="git checkout -"
alias gb="git branch"

alias vim="nvim --clean"
alias vimdiff="nvim --clean -d"
alias nvimdiff="nvim -d"

v() {
  if [[ $# -eq 1 ]]; then
    source $1/venv/bin/activate
  else
    source venv/bin/activate
  fi
}
