alias l="ls -lh --time-style='+%d.%m.%Y %R'"
alias ll="ls -lhA --time-style='+%d.%m.%Y %R'"

alias code="flatpak run com.vscodium.codium"

alias f="find . -name"

alias g="git"

alias vim="nvim --clean"
alias vimdiff="nvim --clean -d"
alias nvimdiff="nvim -d"
